---
- name: Install core-daemons
  xbps: pkg={{ item }} state=present
  with_items:
    - dcron
    - openntpd
    - socklog-void

- name: Configure openntpd
  copy: src=ntp.conf dest=/etc/ntp.conf owner=root group=root mode=0644
  notify:
    -  ntpd

- name: Enable core-daemons
  file: src=/etc/sv/{{ item }} dest=/var/service/{{ item }} state=link owner=root group=root
  with_items:
    - crond
    - ntpd
    - socklog-unix
    - nanoklogd
