---
- name: Copy the void archive
  copy: src=netboot.tar.gz dest=/srv/tftpboot/netboot.tar.gz owner=root group=wheel mode=0644

- name: Install the void archive
  command: tar xvzf /srv/tftpboot/netboot.tar.gz -C /srv/tftpboot creates=/srv/tftpboot/pxelinux.0

- name: Copy the autoinstall files
  copy: src={{ item }} dest=/var/www/htdocs/preseed/{{ item }} owner=root group=wheel mode=0644
  with_items:
    - autoinstall.cfg
    - firstBoot.sh
