---
- name: Create the reposync group
  group: name=reposync state=present

- name: Create the reposync User
  user: name=reposync state=present

- name: Make mirror web-visible
  file: src=/mnt/mirror dest=/var/www/home/mirror state=link force=yes

- name: Allow the web user to read the mirror
  user: name=nginx group=reposync
