---
- name: Install rsync
  xbps: pkg=rsync state=present

- name: Create mirror directory
  file: path=/mnt/mirror/void state=directory owner=reposync group=reposync mode=0755

- name: Install sync service (1/3)
  file: path=/etc/sv/void-mirror state=directory owner=root group=root mode=0755

- name: Install sync service (2/3)
  copy: src=void-mirror.run dest=/etc/sv/void-mirror/run owner=root group=root mode=0755

- name: Install sync service (3/3)
  file: src=/etc/sv/void-mirror dest=/var/service/void-mirror state=link

- name: Install nginx location
  copy: src=void-mirror.conf dest=/etc/nginx/locations.d/{{ jekyll_site_url }}/void-mirror.conf owner=root group=root mode=0644

- name: Install mirror rules
  copy: src=mirror.rules dest=/etc/iptables.d/mirror.rules owner=root group=root mode=0640
  notify:
    - iptables

