---
gw_network: 192.168.1.0

dhcp_self: 192.168.1.1
dhcp_lower: 192.168.1.2
dhcp_upper: 192.168.1.50

domain: lug
domain_address: 129.110.92.80
hostname: lugbox

dns_SOA: 2016093000

int_if: fxp0
ext_if: bge0

boot_fname: pxelinux.0
boot_next: 192.168.1.1

ntp:
- pool.ntp.org

staticHosts:
  lug-cardboard:
    mac: 00:0f:b5:46:9c:c2
    addr: 192.168.1.3
    name: lug-cardboard
  office01:
    mac: c8:9c:dc:6d:20:ba
    addr: 192.168.1.10
    name: office01
  luglab00:
    mac: 00:1c:23:29:df:38
    addr: 192.168.1.20
    name: luglab00

stubZones:
  UTD:
    name: utdallas.edu
    addresses:
      - 10.180.15.160
      - 10.182.70.107
