---
gw_network: 192.168.1.0

dhcp_self: 192.168.1.1
dhcp_lower: 192.168.1.2
dhcp_upper: 192.168.1.50

domain: lab.lug.utdallas.edu
hostname: lugbox

dns_SOA: 2016041301

int_if: fxp0
ext_if: bge0

boot_fname:
boot_next:

ntp:
- pool.ntp.org

staticHosts:
  lug-cardboard:
    mac: 00:0f:b5:46:9c:c2
    addr: 192.168.1.3
    name: lug-cardboard

stub-zones:
  UTD:
    name: utdallas.edu
    addresses:
      primary: 10.180.15.160
      secondary: 10.182.70.107
