---
- name: Add SSH banner
  copy: src=ssh_banner dest=/etc/ssh/banner owner=root group=root mode=0644
  notify:
    - sshd

- name: Configure sshd
  template: src=sshd_config dest=/etc/ssh/sshd_config owner=root group=root mode=0644
  notify:
    - sshd
